Issue558
ichimomo/frasyr pull request #560
Opened 2021-03-29 09:20 UTC by fshin3

JackknifeSR でsteepness(h, B0, R0, SB0)出力

2021-04-08 05:42 UTC, fshin3 commented
プルリク重複してました

2021-04-08 06:03 UTC, fshin3 commented
JackknifeSR のプロットでsteepness(h, B0, R0, SB0)を出力できるようにした。

2021-04-19 06:16 UTC, ichimomo commented
fit.SRを含め、bio_parを与えると、こんな出力が出て、ジャックナイフでもこんな図が出ますよみたいなexample codeもついでにあげておいてください

2021-04-19 06:32 UTC, ichimomo commented on R/stock_recruit.r
>  #' }
これだとbio_parが定義されていないので、動かないですよね　bio_parを定義して、コピペしたときに動くようなexampleにしてあげてください

2021-04-19 06:33 UTC, fshin3 commented
これまでの出力
![jackknife_pars](https://user-images.githubusercontent.com/28075069/115191437-63314500-a124-11eb-98c6-6a156df39ef8.png)
に加えて
![jackknife_steepness](https://user-images.githubusercontent.com/28075069/115191496-78a66f00-a124-11eb-81e7-969b20d33819.png)
が出力されます

2021-04-19 06:36 UTC, fshin3 commented on R/stock_recruit.r
>  #' }
111行目に定義してますう。。

2021-04-20 02:49 UTC, fshin3 commented
bio_parsを使うときの説明を長めに書きましたが、どうでしょうか。

2021-04-20 03:10 UTC, ichimomo commented
どうもありがとうございます！　図もありがとうございます．やっぱりｈとかが出力されるのはいいですね　（^^ ）
で，すみませんもう一点，すべての図において，y軸の最小値をゼロにしていただけないでしょうか？ 
+ scale_y_continuous(limits = c(0, NA)) でできると思います（pull requestでなくてすいません）

これ追加してどんなグラフになるかまたここに貼ってください　
ご面倒ですがよろしくお願いします

2021-04-20 09:36 UTC, ichimomo requested changes

2021-04-20 09:36 UTC, ichimomo commented on R/stock_recruit.r
>  #' }
あ、すみませんされてましたね、、

2021-04-21 04:52 UTC, fshin3 commented
あ、これggplotじゃないですね。とりあえず修正したということで（引数のylim.range=(0.5,1.5)を(0,1.5)にしました）。ggplotもこのあと作りますう。
![jackknife_pars](https://user-images.githubusercontent.com/28075069/115498355-635a4d80-a2a8-11eb-835a-462ce7f57ab1.png)
![jackknife_steepness](https://user-images.githubusercontent.com/28075069/115498365-681f0180-a2a8-11eb-832c-2c76b3de71e0.png)

2021-04-22 04:05 UTC, fshin3 commented
ggplot化は別issueとしてひとまずジャックナイフでスティープネスの図も出力、でマージしてもらえますか？

2021-05-12 03:17 UTC, merged

2021-05-12 03:18 UTC, ichimomo commented
マージ遅くなってすみません，マージしました