fix do_caaboot_vpa #752
ichimomo/frasyr pull request #754
Opened 2022-07-25 04:42 UTC by KoHMB

CAAのブートストラップ法の修正
C_tは対数正規分布で乱数生成（平均値の補正あり）
C_a,tはt年の各年齢の漁獲割合を基に、多項分布で乱数生成

2022-08-01 01:54 UTC, ichimomo requested changes

2022-08-01 01:54 UTC, ichimomo commented on R/diagnostics_vpa.R
> +                         rmultinom(1,.x,.y)
こちらで，多項分布を仮定したリサンプリングしていると思いますが，このときのサンプルサイズはどのように仮定していますか？サンプルサイズ＝catch at ageの尾数ですか？　そうするとcatch at ageの尾数の単位に誤差の大きさが依存してしまうので，普通はサンプルサイズは外部から引数として与えるのが良いと思います（B_cvのような，分散の大きさを規定する引数，サンプルサイズが大きいほど分散は小さくなる）　規定値はだいたい200くらい？でどうでしょうか？

2022-08-30 02:41 UTC, KoHMB commented
有効サンプルサイズ（ESS）の引数を設定
デフォルトは200。いろいろ数字を変えてみたが、50だと明らかに広い感じ。逆に300で最近年広がっているのは、ただのモンテカルロエラーか？
![Rplot](https://user-images.githubusercontent.com/64621188/187336376-a9c8bc1f-5296-4124-94a5-2028dd922b2c.jpeg)

2022-09-14 11:32 UTC, KoHMB commented
もともとテストデータのスケールが小さいため、ESS100以降の変化が見えにくい。
ESS50は不確実性広め
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABMIAAALaCAYAAADTIv9sAAAgAElEQVR4Aezd65WrOrOFYef0/XNAHU9Hs6LYGXQMJwbOwIZujLmLkkE8e481jEHo8lYhJrNl+1b5DwEEEEAAAQQQQAABBBBAAAEEEEAAgQsQuF1gjIaIAAIIIIAAAggggAACCCCAAAIIIIBAxQiTBAgggAACCCCAAAIIIIAAAggggAAClyDACLtEmA0SAQQQQAABBBBAAAEEEEAAAQQQQIARJgcQQAABBBBAAAEEEEAAAQQQQAABBC5BgBF2iTAbJAIIIIAAAggggAACCCCAAAIIIIAAI0wOIIAAAggggAACCCCAAAIIIIAAAghcggAj7BJhNkgEEEAAAQQQQAABBBBAAAEEEEAAAUaYHEAAAQQQQAABBBBAAAEEEEAAAQQQuAQBRtglwmyQCCCAAAIIIIAAAggggAACCCCAAAKMMDmAAAIIIIAAAggggAACCCCAAAIIIHAJAoywS4TZIBFAAAEEEEAAAQQQQAABBBBAAAEEGGFyAAEEEEAAAQQQQAABBBBAAAEEEEDgEgQYYZcIs0EigAACCCCAAAIIIIAAAggggAACCDDC5AACCCCAAAIIIIAAAggggAACCCCAwCUIMMIuEWaDRAABBBBAAAEEEEAAAQQQQAABBBBghMkBBBBAAAEEEEAAAQQQQAABBBBAAIFLEGCEdcP876u63W7z/77+dc96bP/8+66+7veXc+/3r+r7389b2XbHlnPac+def75f+9Id13v3f6p/31/V/Xfs9+rr+1813vO51vc+/lN932/V7f792qeffD2M47kz+6kcvh8trmvzJJHVz7/eNXqv7l9HyvO1PJRHAAEETkZg6h71q0Fu1e1dqFRbNNOWcxYTXXVPWXP/WlN2cW8VRAABBBBAAIEOAUZYB0a1UaD9+xo3nWoDqn7Y7v+35Zx+HVPv/32NG3r97oyW7RecajD02LsR9vMw7r6qd7IxHRlldLtVfUyjZfsFq6paU3bRyJbk8EA/FtX94UJJrH6+O0Zv79q458ujDyPUPAIIIPBZAkvuUbUh1rtPbdFMW85ZDGflPWXN/WtN2cX9VRABBBBAAAEEXggwwro4GoHW01/dEu/bv2Lo/rb66+enXiX2fOh+qXPLOe8tT+x5N45GC7eitDYD2gVWj79yDvR7tJL8B55CMZeBEcQzgv1UDv/G9V59t7HOH7ptLSaxauL3MC07A//591xpWJvVpwOyDaOzEEAAgY8SmLpHjXVsi2bacs5Y+2/7V95T1ty/1pR965cdCCCAAAIIILCUACOsS2qDQGs/MvdidHXrbMVYp8CWc7pVzm//q74G/qI6dN7TUBowRgb6PXT+p/blNcJieIawn8vh5vjZjJ80VlPxmzr2qezWLgIIIFAogbl71MCwt2imLecMND2ya+q+8X5szf1rTdmRztmNAAIIIIAAAgsIMMK6kDYItPbjlB2fq1vj8Pbqdhph1f3+jLftzuqoxsSaNzumVjpNHRse1nNv57zOirjbrf5+qs5qnKkq3o516qya7e74u/DrVT4vH1Ud+l6sI/Dsjqk/4Klj/bK993O5NXe8V93g29+VZc9Vg/f7999qwt+Pew6Yq1XD/fFdb2tiMMVj6thg73s7m350c6hXwlsEEEAAgZ0IbLkHZTlnzT1pikX/njJ1j+of67/vtjN1rFvONgIIIIAAAggsIcAI61LaIrY6xsz96/vx8ch5u6cRNI/vD1tyzkqB1o7j+/XLwev+/X788THuvmDrwmi/v6pjsL0eHnn3N7buF/S32/Pm3FC1XQE4UH9rYrSr2LomWbvdlnlUfwSeEewfLtTjBxtehtsi/TWw1sa0raCqqlHGnTqb/HuLdZuXjy92WxODIFb1sMb62hmyTQQQQACBnQi83AeW1vl33z+Mzhrr+ts9Zc39a03ZsQ7YjwACCCCAAAJLCDDCupQaAdOaNsOvQytdfnqrkNqVMlO/GrnlnG5nx7fbjwTM9z9CdP0J1vrLbltT8LdPgw7N+FieR7pG2HPP8+MDHfPldyVS/X1Pf+1W1U/VfmHupqYf3s/UjyF082ENzzVl5/h0js/m8P3ty/07Z89s/sX2z+Sqf93qyeeP7/DYhmI202BzeLi+9tzN9bamXv/XSNuKvSKAAAII7Etg9h5V66fufbVtfotm2nJO296G18F7ypr715qyG/rnFAQQQAABBBD4JcAI+0Xxtzpk2EB6mlvDAq2t5Kf6+Vd/NO+rujdfkv+oa/JBe8s5bXvDr09jYNwQ+vs1pgjR1ZolryZV9fKxuOF+j+9dYIS1AvTPjelU15w/eKxTbGQzhmcE+2U5XP+KaWtQjgx5ZPd0n7snvZtTy8/t1vPcnj73va33Gt72tPky+MD1VtoOBBBAAIE9CGw2wtrGt2imLee07S18Hb2nrLl/rSm7sF+KIYAAAggggMAgAUZYF0sj0Db6Jd2amu2/1TJ/5tNAsZddQ+c04qj9mN/ga994eqn0tz/fD4OuLRshut5Nq2fjY/uH+tnf937um/nxK0Jbw3Lg9deQPALPCPZ/RthwDv/l1t+Krj7rifcN40Xn9q+l/vvWGB3M5TZ2MXn6uzqx+0upE8N2CAEEEEBgJwJv94LUev/ua5/SWdP3lDX3+jVlU7k5HwEEEEAAgWsTYIR1479aoDWi5ddg6VbWbjcmzq33UL/lnEWmQdvu8OurgfRuMP2dNXXsr9T71th5Y/vfa3jf837u6zimvruqNVXq114MPsrzfUx/45469ldqcGs2hxPqXmOEtd+d93Dkhtpsrp1FMRg6vx391LG2TPvalK3bnLz+2vJeEUAAAQR2JTB7j+q3dmSdteSeMnWP6h/rv++ymDrWLWcbAQQQQAABBJYQYIR1Ka0WaO0Xyg99n0VbcSNefk2Ybee0tc2/TonGdyH1NJQG+t+usBpeWjTRjfc2noXH9k9U9Xvo/dwxI2zRaqXfepdsxPHcn/3cirB6vA3LTj4uofAs07BYmBPPv5J/Vf9WGWjDvUln1Y67/sjwtg+GDvfMXgQQQACBxQSK0Fn1aJffU9bcv9aUXcxcQQQQQAABBBB4I8AI6yLZINDaX52rvzvs6+VL2mud9K96fhTxVr0s2W/aWXVOt58z208hdatevguq05cXI6DtS/djYr+/Lnjb8MXq76bVs7tj+2cG8zj8fu67WGxFaR2Hn5fvwPr591Xd61VACw2cfo/CeO7Ofs4I2/IRki6NlnGdF39m0s+/72G+jQH29VV/mf6A2dqtem47kVUbw40pMNc7xxFAAAEElhBo5vJVc3E7/x9QZy0aR9v/JTprTdklvJVBAAEEEEAAgUECjLAullaATH5cq/sRu+fJv98PMXZeLX667Tw+yTf1S4T1R7fez+lVMfG2Wbkz1J+Bj4S1JsHbjwT0FN5znHOGxrtp1VB6moID7U8MpDn0XucL87af7Sq2oXEnGTExPOvB7cv+zwh7i+ULk7kYTkRklPFQnX/G2R4fRdzMarTPQx+bnRi7QwgggAACaQRK0Fkb7ilL71813DVl04LhbAQQQAABBK5LgBHWjf1GgVZX8fNYRXV/roxpTYf7wCqxTntbzumcPr1ZrwB7rMRpH/bvryvEXs5+rhR6rJp69H2430cywh6/Qtn+MmfXXHsbd70y7rvqLGB6GfniN2/1pvN8tr0n+zkjrO7zPiy+WvZ1vnT/yt0D2hqWL6sQe2WWv93IatF1nWI8Lx+BkggggMClCSyaj9//4Fgz26KZtpwzG59FY+jfU5bdv55tryk721sFEEAAAQQQQGCAACNsAIpd4wT+fQ2t/Bkv78h+BLDfj6WaEEAAAQQQQAABBBBAAAEErkmAEXbNuG8cdf0Rwf5fOTdW5bSVBLBfCUxxBBBAAAEEEEAAAQQQQAABBN4IMMLekNgxSuDf1+OL6EePLz2w6GMFfx/p9CN/z4881j8CsOt/4rArTpUhgAACCCCAAAIIIIAAAggcnwAj7PgxKq+HDJhjxFQcjhEHvUAAAQQQQAABBBBAAAEEEMhGgBGWDbWGEEAAAQQQQAABBBBAAAEEEEAAAQQ+SYAR9kn62kYAAQQQQAABBBBAAAEEEEAAAQQQyEaAEZYNtYYQQAABBBBAAAEEEEAAAQQQQAABBD5JgBH2SfraRgABBBBAAAEEEEAAAQQQQAABBBDIRoARlg21hhBAAAEEEEAAAQQQQAABBBBAAAEEPkmAEfZJ+tpGAAEEEEAAAQQQQAABBBBAAAEEEMhGgBGWDbWGEEAAAQQQQAABBBBAAAEEEEAAAQQ+SYAR1tC/3W7V//73P/8wkANyQA7IATkgB3bLgU+KvCO1TWfRmHS2HJADckAOyIE9cyBF5zDCOkZYCkjnIoAAAggggAACXQK12PPfk0BthPkPAQQQQAABBBDYg0CqxqJKmigQaHukozoQQAABBBBAoCWQKtLaekp4pbNKiKIxIIAAAgggcAwCqRqLEdbEkUA7RkLrBQIIIIAAAqUQSBVppXCox0FnlRRNY0EAAQQQQOCzBFI1FiOsiR+B9tlE1joCCCCAAAKlEUgVaSXxoLNKiqaxIIAAAggg8FkCqRqLEdbEj0D7bCJrHQEEEEAAgdIIpIq0knjQWSVF01gQQAABBBD4LIFUjcUIa+JHoH02kbWOAAIIIIBAaQRSRVpJPOiskqJpLAgggAACCHyWQKrGYoQ18SPQPpvIWkcAAQQQQKA0AqkirSQedFZJ0TQWBBBAAAEEPksgVWMxwpr4EWifTWStI4AAAgggUBqBVJFWEg86q6RoGgsCCCCAAAKfJZCqsRhhTfwItM8mstYRQAABBBAojUCqSCuJB51VUjSNBQEEEEAAgc8SSNVYjLAmfgTaZxNZ6wgggAACCJRGIFWklcSDziopmsaCAAIIIIDAZwmkaixGWBM/Au2ziax1BBBAAAEESiOQKtJK4kFnlRRNY0EAAQQQQOCzBFI1FiOsiR+B9tlE1joCCCCAAAKlEUgVaSXxoLNKiqaxIIAAAggg8FkCqRqLEdbEj0D7bCJHtv7ff1W197/I/qobAQQQQKAMAqkirQwKz1HQWSVF01hKJvBfNfx/yWM2NgQQOB+BVI3FCGtiTqAdP/n3NrMi6zs+TT1EAAEEEIgmkCrSovuXs346KydtbSGwjMCw5TW+d1mtSiGAAALxBFI1FiOsiRGBFp+s3RYiTagz1N1lYRsBBBBAoEwCqSKtJCp0VknRNJazERi3ttYfOdvY9RcBBMokkKqxGGFNXhBo2y6QM5hOZ+vjtkg4CwEEEEDgaARSRdrRxpPSHzorhd55z11vszzPOO+IP9/zrczXnPf5UeoBAghcnUCqxmKENRlEoK27lM5mLpXU33WRUhoBBBBA4FMEUkXap/od0S6dFUH1GHWuMVD2KnuMkX+2F3ux3FrPZ0evdQQQuDqBVI3FCGsyiEBbdimVZCiVOpZlkYwv9Qm+8aPSAgIIILCcQKpIW97S2pL/qq/bvfr+6Z33813db7eq1kS//+7fVbfYv6/xY73aXt7SWS84Tvdmq1nyqfNOB3imw5/iONfuTLcdRgABBMIIpGosRlgTGgJtOkc/YWpoc/9fu7wC0+lMdhQBBBDIRyBVpEX19GlmDRhh/76qW8/46vbh5/veOf5Tfd9v1e3rX7fI6DadNYrmMAfmTI9Sjh8G+EhHzsZ5ZBh2I4AAAqEEUjUWI6wJD4E2nKdXME6MsTzDbTib7UUAAQTyEkgVafv3tl4J1q7oejfCHkbXqLH1PPflcG2c3b6qJVYYnbV/NLfWeDajJXd/t3Jde17ucUW2t3bsyiOAAAKpBFI1FiOsiQCB9pqKzKHyzKGrxfQ1o71DAAEE8hNIFWm797g2rmon6/ERyHcjrF4pdn/7vGTTi8FzBsyxkU7TWSNggnZHmh5Xr3tLyK7AbAsX5yCAAAJbCaRqLEZYQ55Ae4K4mllivGUbflsnVuchgAACexBIFWl79GGwjglT636//30/WHe11+Dqr3EjrB579x+dNRiJpJ1XMFeM8VwEkhLayQgggMAKAqkaixHWwL66QGMIlW0IXTm+K+ZTRRFAAIFdCaSKtF07061syAh77OutCHvsaz76OGGEja4i67R5dZ3VQbFq81w2iN4i8N+q/FYYAQQQ2EogVWMxwhryVxVoVzZIjP065t/WCdZ5CCCAQAqBVJGW0vbkuUNG2OAJnRVfE0bYy/eGDdZTPVaZjRyyu0eAmYLA2Qn0UtpbBBBAYHcCqRqLEdaE5GpGGBPoOiaQWD9jvfvsq0IEEEBghkCqSJupfvvhLUbY4Dkdo2ymN1fTWTM43g6f3fjQfwT6BN6S3A4EEEBgRwKpGosR1gTjKgKNKcIAu3oO7Dj/qgoBBBCYJJAq0iYrTzk4ZGqNrvhqv1R/wPQaPGe4Y1fRWcOjf9/bNw28R6BEAu+Zbw8CCCCwD4FUjcUIa+JQukC7uvlh/AzAbg7sM/2qBQEEEJgmkCrSpmtPODpkhFU/1ff9Vr18zLE2uu7f1U/TVP2rkn/vn+Ufv0K5oCul66wFCKoSjQ5jQmCOwJJrQxkEEEBgLYFUjcUIa4iXKtC6D/+2mUFy4C8H1k62yiOAAAJrCaSKtLXtLS4/aITVZz9XfdWa6PGvY4K1dT/MsPb4i2vWlhh+LVVnDY/2b++cSeA4Alcg8HdF2EIAAQT2IZCqsRhhTRxKEmjMjj+zAwsspnJgn2lYLQgggMAwgVSRNlzrOfeWpLOmInAFU8MYEdhCYOq6cQwBBBBYSyBVYzHCGuIlCLSpB37HGEJyYDgH1k66yiOAAAJLCaSKtKXtnKFcCTprjPMWU8A5CFyRwNg1ZD8CCCCwlkCqxmKENcTPLNAYHMMGBy64LM2BtROv8ggggMASAqkibUkbZylzZp3VZ3xFA8OYEdiLQP968h4BBBDYQiBVYzHCGupnFGhLH/KVYwjJgfkc2DIBOwcBBBCYIpAq0qbqPtuxM+qsLuO9TAD1IIDAf91LyzYCCCCwiUCqxmKENdjPJNCYGvOmBkYYbcmBTbOwkxBAAIERAqkibaTaU+4+k85qATMsEEAgjkB7nXlFAAEEthBI1ViMsIb6GQTalgd75zCE5MD6HNgyGTsHAQQQ6BNIFWn9+s78/hQ6q4p76FczAgi8EzjznKbvCCDwWQKpGosR1sTvyAKNkbHeyMAMs9Qc+OzUrnUEECiBQKpIK4FBO4aj6qz3R3N7EEAgJ4F2jvCKAAIIrCGQqrEYYQ3tIwq01Ad55zOD5EBaDqyZjJVFAAEE+gRSRVq/vjO/P5LOyvmQry0EEJgncOa5Td8RQOAzBFI1FiOsiduhBNp/aQ/vzA/85MB+OfCZqV2rCCBQAoFUkVYCg3YMn9RZ84/hSiCAwKcJtHOFVwQQQGAJgVSNxQhrKH9SoLWBZl7sZ15gieWeOdBeo14RQACBNQRSRdqato5eNrfO+vRDvfYRQGA9gaPPY/qHAALHIZCqsRhhTSxzC7RuCu35wK4uBpAciMmB7jVrGwEEEFhCIFWkLWnjLGWiddb6R25nIIDAEQmcZU7TTwQQ+CyBVI3FCGviFy3QhtKEYRFjWOCKa1QODF3H9iGAAAJjBFJF2li9Z9wfrbOO+ECvTwggsI3AGec4fUYAgbwEUjUWI6yJV7RA66ZF1EO6ehlAciA+B7rXsm0EEEBgikCqSJuq+2zHonXWtsdtZyGAwFEJnG2O018EEMhLIFVjMcKaeIULNF+AXzFp4k0ajPMxzjvVaw0BBM5IIFWknXHMY30O11nVUR/n9QsBBLYSGJtP7EcAAQRSNRYjrMmhcIHGCGOEyYHicsAtCAEEEJgikCrSpuo+27FwncUIQwCBIgmcba7TXwQQyEMgVWMxwpo4hQ [...]

2022-09-15 02:27 UTC, merged